build:
  version: "3.2"

accounts:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    # -----------------------------
    # Shared default CB policy
    # -----------------------------
    configs:
      default:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-size: 20
        permitted-number-of-calls-in-half-open-state: 2

  retry:
    configs:
      default:
        max-attempts: 3        # 1 initial + 2 retries
        wait-duration: 200ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.io.IOException
          - feign.RetryableException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
          - java.lang.NullPointerException

    # -----------------------------
    # Service-level CB instances
    # -----------------------------
    instances:
      loans:
        base-config: default
        wait-duration-in-open-state: 15s   # Loans recovers slower

      cards:
        base-config: default
        wait-duration-in-open-state: 5s    # Cards recovers faster

logging:
  level:
    io.github.resilience4j.retry: DEBUG
    org.springframework.cloud.openfeign: DEBUG
info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"