build:
  version: "3.2"

accounts:
  message: "Welcome to EazyBank accounts related local APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    # -----------------------------
    # Shared default CB policy
    # -----------------------------
    configs:
      default:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-size: 20
        permitted-number-of-calls-in-half-open-state: 2

    # -----------------------------
    # Service-level CB instances
    # -----------------------------
    instances:
      accounts-loans-cb:
        base-config: default
        wait-duration-in-open-state: 15s   # Loans recovers slower

      accounts-cards-cb:
        base-config: default
        wait-duration-in-open-state: 5s    # Cards recovers faster

info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"