spring:
  cloud:
    gateway:
      routes:
        - id: accounts-service
          uri: lb://ACCOUNTS
          predicates:
            - Path=/eazybank/accounts/**
          filters:
            - "RewritePath=/eazybank/accounts/(?<segment>.*), /${segment}"
            - name: CircuitBreaker
              args:
                name: accountsCB

        - id: loans-service
          uri: lb://LOANS
          predicates:
            - Path=/eazybank/loans/**
          filters:
            - "RewritePath=/eazybank/loans/(?<segment>.*), /${segment}"
            - name: CircuitBreaker
              args:
                name: loansCB

        - id: cards-service
          uri: lb://CARDS
          predicates:
            - Path=/eazybank/cards/**
          filters:
            - "RewritePath=/eazybank/cards/(?<segment>.*), /${segment}"
            - name: CircuitBreaker
              args:
                name: cardsCB
      refresh:
        enabled: true