spring:
  cloud:
    gateway:
      routes:
        - id: accounts-fetchCustomerDetails
          uri: lb://ACCOUNTS
          predicates:
            - Path=/eazybank/accounts/fetchCustomerDetails
          filters:
            - "RewritePath=/eazybank/accounts/(?<segment>.*), /${segment}"
            - name: CircuitBreaker
              args:
                name: accounts-gateway-CB
                fallbackUri: forward:/contactSupport
        - id: accounts-service
          uri: lb://ACCOUNTS
          predicates:
            - Path=/eazybank/accounts/**
          filters:
            - "RewritePath=/eazybank/accounts/(?<segment>.*), /${segment}"
            - name: CircuitBreaker
              args:
                name: accounts-gateway-CB
                fallbackUri: forward:/contactSupport
            - name: Retry
              args:
                retries: 3
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1000ms
                  factor: 2
                  basedOnPreviousValue: true
              

        - id: loans-service
          uri: lb://LOANS
          predicates:
            - Path=/eazybank/loans/**
          filters:
            - "RewritePath=/eazybank/loans/(?<segment>.*), /${segment}"
            - name: CircuitBreaker
              args:
                name: loans-gateway-CB
            - name: Retry
              args:
                retries: 3
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1000ms
                  factor: 2
                  basedOnPreviousValue: true

        - id: cards-service
          uri: lb://CARDS
          predicates:
            - Path=/eazybank/cards/**
          filters:
            - "RewritePath=/eazybank/cards/(?<segment>.*), /${segment}"
            - name: CircuitBreaker
              args:
                name: cards-gateway-CB
            - name: Retry
              args:
                retries: 3
                methods:
                  - GET
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 1000ms
                  factor: 2
                  basedOnPreviousValue: true
      httpClient:
        connect-timeout: 1000
        response-timeout: 5s
      refresh:
        enabled: true
resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-size: 20
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2

    instances:
      accounts-gateway-CB:
        base-config: default

      loans-gateway-CB:
        base-config: default
        permitted-number-of-calls-in-half-open-state: 4

      cards-gateway-CB:
        base-config: default

  timelimiter:
    configs:
      default:
        timeout-duration: 10s

    instances:
      accounts-gateway-CB:
        base-config: default

      loans-gateway-CB:
        base-config: default

      cards-gateway-CB:
        base-config: default