spring:
  cloud:
    gateway:
      routes:
        - id: accounts-service
          uri: lb://ACCOUNTS
          predicates:
            - Path=/eazybank/accounts/**
          filters:
            - "RewritePath=/eazybank/accounts/(?<segment>.*), /${segment}"
            - "AddResponseHeader=Response-Time, #{T(java.time.LocalDateTime).now()}"

        - id: loans-service
          uri: lb://LOANS
          predicates:
            - Path=/eazybank/loans/**
          filters:
            - "RewritePath=/eazybank/loans/(?<segment>.*), /${segment}"
            - "AddResponseHeader=Response-Time, #{T(java.time.LocalDateTime).now()}"

        - id: cards-service
          uri: lb://CARDS
          predicates:
            - Path=/eazybank/cards/**
          filters:
            - "RewritePath=/eazybank/cards/(?<segment>.*), /${segment}"
            - "AddResponseHeader=Response-Time, #{T(java.time.LocalDateTime).now()}"
      refresh:
        enabled: true